FROM ubuntu:22.04

ENV TZ=Europe/Madrid \
    DEBIAN_FRONTEND=noninteractive

# Install python3.11.7
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.11 python3.11-dev python3.11-distutils python3.11-venv

# Install curl and network tools
RUN apt-get install -y curl net-tools

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.11 get-pip.py

# Upgrade pip
RUN python3.11 -m pip install --upgrade pip

# Install gcc and git
RUN apt-get update && apt-get install -y build-essential gcc g++ clang git make cmake

WORKDIR /fedstellar
COPY requirements.txt .
# Install the required packages
RUN python3.11 -m pip install --ignore-installed -r requirements.txt