server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: localhost
          agent: promtail
          __path__: /var/log/nginx/*
    pipeline_stages:
      - json:
          expressions:
            http_user_agent:
            request_uri:
      - drop:
          source: http_user_agent
          expression: "(bot|Bot|RSS|Producer|Expanse|spider|crawler|Crawler|Inspect|test)"
      - drop:
          source: request_uri
          expression: "/(assets|img)/"
      - drop:
          source: request_uri
          expression: "/(robots.txt|favicon.ico|index.php)"
      - drop:
          source: request_uri
          expression: "(.php|.xml|.png)$"